1. Create a NumPy array with 10 random integers and print the array to the console.

In [1]:
from numpy.random import seed
from numpy.random import randint 
# Seed random number generator
seed(1)
arr = randint(0, 10, 10)
print(arr)

[5 8 9 5 0 0 1 7 6 9]


2. Find the maximum value in a NumPy array with 50 random floats.

In [3]:
import numpy as np
arr = np.random.randn(50)
max = np.max(arr)
print(arr)
print("Max =", max)

[ 0.58829416  0.34685933  1.3670327   0.67371607 -1.2915627  -0.84824392
 -0.16659957  0.91719602  0.08025059  0.22823877 -0.8804768   0.27812885
 -0.07015677  0.62958793 -1.81342356  1.54744858  0.32505743 -0.21191292
 -1.54672407  1.04520063  1.01037548  0.07083664  0.71758983 -0.25070491
 -0.05152993  0.01312891  0.20223906  0.45495224 -0.39926817  0.18106742
  0.80748795  0.81253519  0.21090203  0.42177915  0.58192518 -0.41020752
  2.2968661   1.68849705  0.62581147 -1.61136381  0.06009774  0.46242079
  0.68483649 -0.59546033  0.99905124 -0.30817074  0.36583834  1.60750704
 -0.23817737 -0.34082828]
Max = 2.2968661024329244


3. Use NumPy to generate a 3x3 identity matrix and print it to the console.

In [ ]:
import numpy as np
array_matrix = np.identity(3)
print('3x3 Matrix')
print(array_matrix)

3x3 Matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Calculate the mean and standard deviation of a NumPy array with 100 random integers.

In [ ]:
import numpy as np
array_100 = np.random.randint(0, 100, size = 100) 
mean = np.mean(array_100)
standard_dev = np.std(array_100)
print("Mean =", mean)
print("Standard Deviation =", standard_dev)

Mean = 51.31
Standard Deviation = 29.124798711750785


5. Create a 2D NumPy array with 5 rows and 5 columns, and then extract the third row and the fourth column.

In [7]:
import numpy as np
array = np.array([[2, 4, 6, 8, 10],
                  [1, 2, 3, 4, 5,],
                  [11, 12, 13, 14, 15],
                  [10, 15, 20, 25, 30],
                  [35, 40, 45, 50, 55]])

# Extract the third row and the fourth column
row = array[2,:]
column = array[:, 3]

# Print the third row and the fourth column
print("The third row =", row)
print("The fourth column =", column)

The third row = [11 12 13 14 15]
The fourth column = [ 8  4 14 25 50]


6. Use NumPy to create a 3x3 matrix with values ranging from 1 to 9, and then print the
matrix to the console.

In [8]:
import numpy as np
# Create a 3x3 matrix with values ranging from 1 to 9
array_matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(array_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


7. Calculate the dot product of two NumPy arrays of length 5.

In [9]:
import numpy as np
# Create 2 arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([4, 6, 8, 10, 12])
# Calculate the dot product of the two arrays above
dot_product = np.dot(arr1, arr2)
print("Dot Product =", dot_product)

Dot Product = 140


8. Reshape a 1D NumPy array with 10 elements into a 2D array with 2 rows and 5 columns.

In [10]:
import numpy as np
# Create a 1D array with 10 elements
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# Reshape the array into a 2D array with 2 rows and 5 columns
new_arr = np.reshape(arr, (2, 5))
print(new_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


9. Use NumPy to calculate the eigenvalues and eigenvectors of a 3x3 matrix.

In [11]:
import numpy as np
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [8, 9, 10]])
# Calculate the eigenvalues, and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues =", eigenvalues)
print('Eigenvectors:')
print(eigenvectors)

Eigenvalues = [ 1.72195445e+01 -1.21954446e+00 -8.86293666e-17]
Eigenvectors:
[[ 0.21654473  0.74555156  0.40824829]
 [ 0.48649286  0.14749127 -0.81649658]
 [ 0.8464237  -0.64992246  0.40824829]]


10. Create a new NumPy array that is the result of concatenating two existing arrays with different shapes.

In [12]:
import numpy as np
# Create 2 NumPy arrays
arr1 = np.array([[1, 2, 3, 4, 5],
                 [2, 4, 6, 8, 10]])
arr2 = np.array([1, 2, 3, 4, 5])
# Concatenate the array
new_arr = np.concatenate((arr1, np.array([arr2])), axis = 0)
print(new_arr)

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 1  2  3  4  5]]
